### ISSUE TITLE
feat: panic prevention lints

### ISSUE THREAD

**Issue by functor-flow** [RaoFoundation/subtensor#516]
Please add the following clippy lints into `Cargo.toml` in all pallets utilizing `on_initalize` :

```toml
[lints.clippy]
arithmetic_side_effects = "deny"
indexing_slicing = "deny"
panicking_unwrap = "deny"
out_of_bounds_indexing = "deny"
```

This will help us improve blockchain safety. Making sure runtime can not panic in on-initilize hook, halting the block production.
